smtp:
  # your smtp server host
  host: ${SMTP_HOST_ADDRESS}
  # your smtp server port
  port: ${SMTP_SERVER_PORT}
  # your smtp server username
  username: ${SMTP_USRENAME}
  # your smtp server password
  password: ${SMTP_PASSWORD}

mail:
  smtp-auth: true
  starttls-enable: true
  debug: true
  transport-protocol: smtp

code:
  # the length of the code
  length: 6
  # should it contain digits?
  digits: true
  # should it contain uppercase letters?
  upper: false
  # should it contain lowercase letters?
  lower: false
  # How long should the code be valid?
  valid-for-minutes: 5

html:
  template:
    # path to the html template
    path: src/main/resources/templates/
    # name of the html template file
    file-name: template
    # name of the variable used for code inside the html template
    variable-name: code

datasource:
  # database url
  jdbc-url: ${DATABASE_URL}
  # database username
  username: ${DATABASE_USERNAME}
  # database password
  password: ${DATABASE_PASSWORD}

security:
  jwt:
    # jwt username (used to get jwt authentication token)
    username: ${JWT_USERNAME}
    # jwt password (used to get jwt authentication token)
    password: ${JWT_PASSWORD}

spring:
  jpa:
    hibernate:
      ddl-auto: create-only
